// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbConCglSb29tU3RhdGUSCwoHV0FJVElO",
            "RxAAEg0KCUdBTUVTVEFSVBABKkYKC1BsYXllclN0YXRlEggKBElETEUQABIK",
            "CgZNT1ZJTkcQARIKCgZJTlRSQVAQAhILCgdPVVRUUkFQEAMSCAoEREVBRBAE",
            "KjoKB01vdmVEaXISCAoETk9ORRAAEgYKAlVQEAESCQoFUklHSFQQAhIICgRE",
            "T1dOEAMSCAoETEVGVBAEYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.RoomState), typeof(global::Protocol.PlayerState), typeof(global::Protocol.MoveDir), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum RoomState {
    [pbr::OriginalName("WAITING")] Waiting = 0,
    [pbr::OriginalName("GAMESTART")] Gamestart = 1,
  }

  public enum PlayerState {
    [pbr::OriginalName("IDLE")] Idle = 0,
    [pbr::OriginalName("MOVING")] Moving = 1,
    [pbr::OriginalName("INTRAP")] Intrap = 2,
    [pbr::OriginalName("OUTTRAP")] Outtrap = 3,
    [pbr::OriginalName("DEAD")] Dead = 4,
  }

  public enum MoveDir {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("UP")] Up = 1,
    [pbr::OriginalName("RIGHT")] Right = 2,
    [pbr::OriginalName("DOWN")] Down = 3,
    [pbr::OriginalName("LEFT")] Left = 4,
  }

  #endregion

}

#endregion Designer generated code
